version: '3'

services:
  db:
    image: testapp-db-cached # Buildxのビルド時に指定したイメージ名
    build:
      context: ./db
      dockerfile: Dockerfile
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u$MYSQL_USER -p$MYSQL_PASSWORD

  app:
    image: testapp-app-cached # Buildxのビルド時に指定したイメージ名
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=test
      - DB_PASSWORD=test