# Use the official MySQL image.
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=yourpassword
ENV MYSQL_DATABASE=testdb
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=test

# Expose port 3306
EXPOSE 3306
