name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 1. Buildxのセットアップ
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # 2. キャッシュ設定
      - name: Cache Docker layers - App
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-app # Buildxのキャッシュを指定
          key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
          restore-keys: |
            ${{ github.ref }}
            refs/head/main

      - name: Cache Docker layers - DB
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-db # Buildxのキャッシュを指定
          key: ${{ github.ref }}-${{ github.sha }} # キャッシュのキーを指定
          restore-keys: |
            ${{ github.ref }}
            refs/head/main

      # 3. Buildxでイメージをビルドする
      - name: Build images - App
        uses: docker/build-push-action@v5
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
          tags: testapp-app-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
          load: true
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache-app # キャッシュを指定
          cache-to: type=local,dest=/tmp/.buildx-cache-new-app # キャッシュを指定

      - name: Build images - DB
        uses: docker/build-push-action@v5
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }} # Buildxでビルドすることを指定
          tags: testapp-db-cached:latest # イメージ名を指定/docker-compose.ymlで参照する名前
          load: true
          context: ./db
          cache-from: type=local,src=/tmp/.buildx-cache-db # キャッシュを指定
          cache-to: type=local,dest=/tmp/.buildx-cache-new-db # キャッシュを指定

      # 4. docker composeビルド/起動
      - name: docker compose build & up
        run: |
          docker compose -f docker-compose.ci.yml build
          docker compose -f docker-compose.ci.yml up -d

      # 5. テスト実行
      - name: Test
        run: |
          docker compose -f docker-compose.ci.yml run --rm app go test -v ./...

      # 6. 肥大化対策
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache-app
          rm -rf /tmp/.buildx-cache-db
          mv /tmp/.buildx-cache-new-app /tmp/.buildx-cache-app
          mv /tmp/.buildx-cache-new-db /tmp/.buildx-cache-db