name: dev-deploy tag

on:
  pull_request:
    types: [closed]
    branches:
      - "master"
      - "main"
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    name: echo deploy tag
    runs-on: ubuntu-latest

    steps:
      # タグプッシュ時にのみ実行するステップ
      - name: Run this step for tags only
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: echo ${{github.ref_name}}
      
      # プルリクエストがマスターまたはメインにマージされたときに実行するステップ
      - name: Run this step for closed PRs to master or main
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: echo "This step is running because a PR was merged into master/main."