name: dev-deploy tag

on:
  pull_request:
    types: [closed]
    branches:
      - "master"
      - "main"
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    name: echo deploy tag
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: echo ${{github.ref_name}}
